name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish x86
      run: dotnet publish -r win-x86 -c Release -o ./publish/win-x86
    - name: Publish x64
      run: dotnet publish -r win-x64 -c Release -o ./publish/win-x64
    - name: Zip Publish Folder
      run: |
        Compress-Archive -Path ./publish/* -DestinationPath ./publish.zip
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: ControlCAN
        path: ./publish.zip
    - name: Create GitHub Release
      uses: gh actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: "Release ${{ github.sha }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to GitHub Release
      uses: gh actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish.zip
        asset_name: publish.zip
        asset_content_type: application/zip
