# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish x86
      run: dotnet publish -r win-x86 -c Release -o ./publish/win-x86
    - name: Publish x64
      run: dotnet publish -r win-x64 -c Release -o ./publish/win-x64
    - name: Upload a Build Artifact x86
      uses: actions/upload-artifact@v4.5.0
      with:
        name: ControlCANx86
        path: ./publish/win-x86
    - name: Upload a Build Artifact x64
      uses: actions/upload-artifact@v4.5.0
      with:
        name: ControlCANx64
        path: ./publish/win-x64
    - uses: Shopify/upload-to-release@v1
      with:
        name: ControlCAN
        path: ./publish/
        repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      
      
